apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rehkb460p-nodejs-gitops
  description: This is GitOps manifest for rehkb460p-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=rehkb460p-nodejs
    backstage.io/kubernetes-id: rehkb460p-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rehkb460p-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rehkb460p-nodejs
